export const FETCH_STOCK_LIST_REQUEST = "FETCH_STOCK_LIST_REQUEST";
export const FETCH_STOCK_LIST_SUCCESS = "FETCH_STOCK_LIST_SUCCESS";
export const FETCH_STOCK_LIST_FAILURE = "FETCH_STOCK_LIST_FAILURE";
